# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-10-06 02:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='last_updated',
            field=models.DateField(auto_now=True, default=datetime.datetime(2018, 10, 6, 2, 34, 6, 589255, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
